clc;
clear all;
img=imread("C:\Users\Iqra\Downloads\nature.jfif");
dct_img = imdct(img);
subplot(1,2,1);
imshow(img);
title('Original Image');
subplot(1,2,2);
imshow(dct_img,rainbowcolormap(32));
title('Discrete Cosine Transform');
