clc;
clear;
img=imread('C:\Users\Iqra\Downloads\nature.jfif');
se1=imcreatese('rect',3,3);
im1=imerode(img,se1);
im2=imdilate(im1,se1);
h=img-im2;
subplot(2,2,1),imshow(img),title('OrignalImage');
subplot(2,2,2),imshow(im1),title('Erotion Image');
subplot(2,2,3),imshow(im2),title('Dilation Image');
subplot(2,2,4),imshow(h),title('Top Hat Transformation Image');
