clc;
clear all;
img = imread("C:\Users\Iqra\Downloads\nature.jfif");
img = rgb2gray(img);
ed_Sobel = edge(img,'sobel');
ed_Prewitt = edge(img,'prewitt');
ed_Canny = edge(img,'canny');
subplot(2,2,1);
imshow(img);
title('Original Image');
subplot(2,2,2);
imshow(ed_Sobel);
title('Sobel Image');
subplot(2,2,3);
imshow(ed_Prewitt);
title('Prewitt Image');
subplot(2,2,4);
imshow(ed_Canny);
title('Canny Image');
